# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-15 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('college', models.CharField(default=b'', max_length=100)),
                ('mobile', models.CharField(default=b'', max_length=13)),
            ],
        ),
    ]
